spring:
  application:
    name: coupon-eureka

server:
  port: 8000

eureka:
  instance:
    # Eureka Server的ip地址
    hostname: localhost
  client:
    # 标志是否从 Eureka Server 获取注册信息，默认是true。如果这是一个单节点的 Eureka Server，不需要同步其他节点的数据，设置为false
    fetch-registry: false
    # 是否将自己注册到 Eureka Server，默认为true。由于当前应用是单节点的 Eureka Server，设置为false
    register-with-eureka: false
    service-url:
      # 设置该 Eureka Server 的访问地址， 查询服务和注册服务都需要依赖这个地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

